#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pre-commit run black --all-files
        pre-commit run doc8 --all-files
        pre-commit run flake8 --all-files
        pre-commit run isort --all-files
    fi
fi
